# Changes here will be overwritten by Copier
_commit: 09af72b
_src_path: https://github.com/worldworm/copier-base.git
copyright_license: MIT
copyright_year_start: 2023
copyright_year_today: 2023
project_description: Copier template for poetry projects with ldap utils.
project_emoji: 📋
project_name: copier-poetry-ldap
repository_name: copier-poetry-ldap
repository_provider: GitHub
repository_url: https://github.com/worldworm/copier-poetry-ldap
repository_username: worldworm

