# Changes here will be overwritten by Copier
_commit: v1.1.0
_src_path: https://github.com/worldworm/copier-base-copier.git
answersfile_suffix: poetry-ldap
copyright_license: MIT
copyright_year_start: 2023
copyright_year_today: 2023
is_bp: false
is_ext: false
is_meta: false
need_trust: true
project_description: Copier template for poetry-ldap projects.
project_emoji: 📋
project_name: copier-poetry-ldap
ref_tech_url: https://github.com/cannatag/ldap3
repository_name: copier-poetry-ldap
repository_provider: GitHub
repository_url: https://github.com/worldworm/copier-poetry-ldap
repository_username: worldworm
warning_early_dev: false

